language: ruby
sudo: required
cache: bundler
bundler_args: --without development
before_install:
  - gem update --system
  - gem --version
stages:
  - name: e2e
    if: type IN (pull_request, cron)
  - name: publish binary
    if: tag IS present
jobs:
  include:
    - stage: e2e
      name: "e2e: bionic docker with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
        - FOOTLOOSE_IMAGE=quay.io/footloose/ubuntu18.04
    - stage: e2e
      name: "e2e: bionic containerd with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=containerd
        - NETWORK_PROVIDER=weave
        - FOOTLOOSE_IMAGE=quay.io/footloose/ubuntu18.04
    - stage: e2e
      name: "e2e: focal docker with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
        - FOOTLOOSE_IMAGE=jakolehm/footloose-ubuntu20.04
    - stage: e2e
      name: "e2e: focal containerd with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
        - FOOTLOOSE_IMAGE=jakolehm/footloose-ubuntu20.04
    - stage: e2e
      name: "e2e: bionic docker with calico"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=calico
        - FOOTLOOSE_IMAGE=quay.io/footloose/ubuntu18.04
    - stage: e2e
      name: "e2e: focal docker with calico"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=calico
        - FOOTLOOSE_IMAGE=jakolehm/footloose-ubuntu20.04
    - stage: e2e
      name: "e2e: centos7 docker with weave"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=weave
        - FOOTLOOSE_IMAGE=quay.io/footloose/centos7
    - stage: e2e
      name: "e2e: centos7 docker with calico"
      script: ./e2e/travis.sh
      rvm: 2.5.4
      dist: bionic
      env:
        - CONTAINER_RUNTIME=docker
        - NETWORK_PROVIDER=calico
        - FOOTLOOSE_IMAGE=quay.io/footloose/centos7
    - stage: publish binary
      script: ./build/travis/macos.sh
      os: osx
      install: ls -l
      env:
        - secure: "gP9kDFjI51wH8DOrZnLFJGvJOOwUIlvkB3gaIKYx17DtNk8D59twiOCbbclQdOzfNtTtgOywlWzJHHBduItwnHZzK/lOodKeJMXT52ne/BZXZ2r1SRoxTFWe7mmvg7xeb5SvLJ8udGYk5OSdR4Denx/3nZyimk7Fwlq5COC9hVfzcIDAn4+IypK2OADj+i6RNeqCdBspatDdXXopbkqoGPlNFhOzdmzqW+1jOFRGT3LkKv4GdlHK5QyxvN72FgpZ522+GzCg/AMVgdvoPN2eZqTscr5bL77K93nYQHhgiZzK2WXgnJ32N58Mu0DS9GGY7oFm1Wf/0unm95q7s31qF6Qv9avY0+pLWbMEu87xd60E8vBC9kl8Lvn2BvOgTPP3kPe8rVUaB+v9mHnE9nyr4vicsy559LSXSqjaS071scwnjcmSRCzzwlj8P/Oyf5fqVwbnCoivGK/LdLecpA/6TXrq3YWEs8a4uhNfLVivktx4t3jRuUUMJkpc7+0Ckuml02kCqqHJjZnot5NRAoK/95hkzyy5BGZ1EN+XPsrVe1NiznhCqcyKn4R/53a0gG2Dj2tws9iK//OAjw70nxpPdrzuXEMhOIMGLsgDJHugbW3Oz0DtcxJlaV3SQFvYUyxNWrAXA6ThVoW/CSovJjmdHVDyfdbz4uvG2CuF5L2EOJg=" # GITHUB_TOKEN

