language: ruby
sudo: required
cache: bundler
bundler_args: --without development
env:
  global:
    - secure: "AX0y/vETBJ4C93/RWgTZNFwlm8r+4b0cWExOa3G4NBvxc3x1PBjA9sD7LOezUxMCaOuTM1GF+vpXupreeZtdU6mUqQNJSsOH5sWivPfQwCmxbhODW/CGhlhKZT0pTJQ2QhUbp6zXeLfQ3WJT4X4VH2NP5zkfJ7Q0hO7AJqqty/+mAZLbtaBkw1eKhwWPx1t3UQx9zY07V2WsJQCmj9O/bdMyoa3uoTvSahzvAQsY/1XQ6OMZrVvt7JGoFjEVLNnttT3at3HvG3Izwb8u+ftrCr+0u6V9tUPAH+1WHJgP1fYrysU2n+HwhvGYlkl3TYt0wxP9ccz18NiFGf3SOf+OSBQJ11cQ6RJ7R6Qo/RLpW2AffjYW881d32pORbVsEpj8vBvElfJKbl0rT4IgIRJxxCuZnqVbX+8szma9EAmltGbtNdyuX4WxARZ3XNlFONacX5mnubRZDruYijNPzv3tCb6KBaRV5yfg8dhMPjOf6r0i8r0+9IFRsfszVMSxJhrnXlhtaYn7OikqBDOSiCa/VeSBb09fl/klnTCpCHFRICYgWqO8vf1jWvXLuKtHA7E3Ah4CJTkirY4eFwLMEN2kJ6g28OudWMU/urL4/rRb4LpzlDySy9KFA8f1/+7A/mzLDv7Iket2ig6/Pa7ymnYSlmypzVZTvcpJr0EfK+hmr6E="
stages:
  - name: publish binary
    if: tag IS present
jobs:
  include:
    - stage: publish binary
      script: ./build/travis/macos.sh
      rvm: 2.4
      os: osx
      deploy:
        provider: s3
        access_key_id:
          secure: "OHjLg4bzJBUdwmw42XK5s/+5tHUy7SO32/NzV5qCETIw+lr0lEhHIUeGUDGEqsMKvB3X1rIyFhhYJcRUCkJHfDUM2uRyIxYl/HUNNHCnZttwBHsn517Wt8sSzx5mSHuqXl54hoI47vvx0yfKrvW70/AF0aNufEde5tQePzsgghZ0FIPKx29CiG0QAufTgJ3B3tXJtDywDXO6kyQmmpjSTO+Rne8YEx4MvyoGH1DhHiiSsggSMrYUy80mZP967AvQ6cCQNS7d9A1ThNjJVNGQ9jzTGW8vWRsvI1Y5583sWwAwVbKSYtcaO2t5IC1q62PnYu9xVyy6D5QZ4uJ4jQk8at00348nj059CosNEE9IdqRaTJi5TIiX9H1nU8y3P/c/2dYpsQIKch0Ji/cQhl4RCe+QQuOpCzggElf8GeD/tg9GJFhX+uPPWFJMl4zvrH5EascRm+PHJsr7UFL0Lv4Q0x85qdCa/0Oh1XA+f+WaLpSkUUiLUUB27+2dLupD3VyuSZ0IferiDHHgIG0teXoSvI6hgSBg85ZYZKls72seTuGG0icrn+U/iz+7ywtaaS5yVmrelUiYq4ElZr3N9SPaWUxUGXo734B60AIJ9dPQQJY8e+TJ2jjX3OCAd//Z3Kh2+O+nbcHUUMY4OfUVp4wcRy2LKlNqPC5DevZij2uVmKM="
        secret_access_key:
          secure: "HCnQTlTJ3jo4oX2ZLXZUUWHOL7yiV/z2dVNTmiQYGJ8Xsf34zLnwRvPTymq4nA7elCmO0J6G2ub1wqBLZqyYHhbhI//9txPpRJmgFf7C3R0c9j5HRG2lxRJ8PNHuOzT5e2Zx1Aq9Aawy2+zXTuNMnTF0gtXg2tO3oHzs2h99mk5qeoLDAbu1HUd+W7ymalbhw+GH3D6X4mHuv/AUowOJuieIMpg/FPvu0/SXh4/KpSV54hlfSDYIqaBlMDxdAJsoJi/tKBegNMkLeXyaFf9PYF6U83P8RABdBkhinatN0b6EJB21mmaRkfVam4gNhEgB+SobZVelmLLAsTZU9kEkt2V4zBgUYUbNI32ZXMhMFsOZtPfInbGAzqZPmKGRh39yFnN92uQjxWJXocGFrk43K3d2lviAntP05+xPpBjO4CDXuC8mqyRZf6vg/Cysu3OuxrUGMru0EHePG6DZDcH8yNq7GcBbarA5+w+hupnfHD8SoRtnSuyPdyPsjGb25vikkgeLN8J8d2FxcUH9NBgeBJXhMcXCKCxmIgCcMtJ1NElip6MktTYMl2nkxDmgpPljUG0QL95fVq88jwWhyxTvpASJvUSDbq0AUWNP5xJ4R+4vlWkSkVrtLhn4IaJ4ou6PATmgzyaw+0EG4JeAT2TfP8z6ILv5NNb/4YThwg08fVA="
        bucket: "pharos-cluster-binaries"
        region: "eu-west-1"
        local-dir: upload
        skip_cleanup: true
        on:
          all_branches: true